---
title: "VCE for real rfMRI data"
output: html_notebook
---

# Read Data

```{r}
covar <- read.csv("out_25753.txt", header=T, sep="")
pheno <- read.csv("pheno_25753.txt", header=F, sep="")
kinship <- read.csv("kinship.csv", header=T, sep="")
```

# Filter Kinship

```{r}
library(dplyr)
idx <- which(kinship$ID1 != kinship$ID2)
kinship <- kinship[idx,]
kinship <- left_join(kinship, covar, by=c("ID1" = "V1"))
kinship <- left_join(kinship, covar, by=c("ID2" = "V1"))
kinship <- kinship[is.na(kinship$Sex.x) == F,]
kinship <- kinship[is.na(kinship$Sex.y) == F,]
kinship <- kinship[,1:3]
```

# Mapping IID and Row/Col

```{r}
for (i in 1:nrow(kinship)) {
    kinship[i, "IDX1"] <- which(kinship[i,1] == covar$V1)
    kinship[i, "IDX2"] <- which(kinship[i,2] == covar$V1)
}
head(kinship)
```

# Build kinship matrix

```{r}
library(Matrix)
n <- nrow(covar)
kin.s <- Diagonal(n, 1)

for (i in 1:nrow(kinship)) {
  kin.s[kinship[i, 4], kinship[i, 5]] <- kinship[i, 3]
  kin.s[kinship[i, 5], kinship[i, 4]] <- kinship[i, 3]
}
```

# Join Pheno

```{r}
covar_pheno <- left_join(covar, pheno, by=c("V1" = "V1"))
```

# Moment-based method

```{r}
nCol <- ncol(pheno) - 1
sigmas.mom <- rep(0, nCol)
deltas.mom <- rep(0, nCol)

system.time({
    for (i in 1:nCol) {
        formula <- as.formula(paste(paste0("V", i+1), "~ Sex + Age + PC1 + PC2 + PC3 + PC4 + PC5 + PC6 + PC7 + PC8 + PC9 + PC10"))
        resid1 <- resid(lm(formula, data=covar_pheno))
        #resid1 <- resid(lm(paste0("V", i+1) ~ Sex + Age + PC1 + PC2 + PC3 + PC4 + PC5 + PC6 + PC7 +
        #             PC8 + PC9 + PC10, data=covar_pheno))
        va1 <- as.numeric((0.5 * (t(resid1) %*% kin.s %*% resid1 - sum(resid1 * resid1)))
                  / ((sum(kin.s * kin.s) - n) / 2))  # sigma_g^2
        if (va1 < 0) {
            va1 <- 0
        }
        sigma <- (sum(resid1 * resid1) / n) - va1 # sigma_e^2
        delta <- va1 / sigma  # sigma_g^2 / sigma_e^2
        sigmas.mom[i] <- sigma
        deltas.mom[i] <- delta
    }
})
# ~1 min for 1485 phenotypes
```

# Check the results

```{r}
head(sigmas.mom)
head(deltas.mom)
```

# Using score function (Trace precalculation)

```{r}
H <- kin.s
precal_length <- 90
d <- 0.01
precal_trace <- rep(0, precal_length) # h = 0.01 ... 0.90
system.time({
for (i in 1:precal_length) {
    H1 <- H
    herit <- d * i
    diag(H1) <- diag(H1) + (1 / herit - 1)
    H1_inv <- solve(H1)
    precal_trace[i] <- sum(diag(H1_inv))
}
})
# 2~3 second per one precalculation
```

# Load precalculated trace 

```{r}
precal_trace <- read.csv("precal_trace.txt", header=F, sep="")
precal_trace <- as.vector(precal_trace)
```


# Define score VCE function

```{r}
score_vce <- function(delta, Y) {
    H <- kin.s
    diag(H) <- diag(H) + delta
    Y <- as.matrix(Y)
    herit <- 1 / (1 + delta)

    if (herit < d) {
        tr <- precal_trace[1]
    } else if (herit > precal_length * d) {
        tr <- precal_trace[precal_length]
    } else {
        idx <- herit %/% d
        remainder <- herit %% d
        tr <- precal_trace[idx] + (precal_trace[idx+1] - precal_trace[idx]) * remainder / d
    }
    # H_inv <- solve(H)
    # tr <- sum(diag(H_inv))
    tr <- as.numeric(tr)
    Hinv_X <- solve(H, X)
    Hinv_Y <- solve(H, Y)
    
    A1 <- t(X) %*% Hinv_X
    A2 <- t(X) %*% Hinv_Y
    A1_INV <- solve(A1)
    
    Hinv_e <- (Hinv_Y - Hinv_X %*% A1_INV %*% A2)
    R <- t(Y - X %*% A1_INV %*% A2) %*% Hinv_e
    sigma_sq <- R / n
    
    # LL <- 0.5 * (-n * log(2 * pi * sigma_sq) - log(det(H)) - n)
    dLL <- 0.5 * (tr - (sum(Hinv_e * Hinv_e) / sigma_sq))
    return (as.numeric(dLL))
}

sigma_sq <- function(delta, Y){
    H <- kin.s
    diag(H) <- diag(H) + delta
    Y <- as.matrix(Y)
    
    Hinv_X <- solve(H, X)
    Hinv_Y <- solve(H, Y)
    
    A1 <- t(X) %*% Hinv_X
    A2 <- t(X) %*% Hinv_Y
    A1_INV <- solve(A1)
    
    Hinv_e <- (Hinv_Y - Hinv_X %*% A1_INV %*% A2)
    R <- t(Y - X %*% A1_INV %*% A2) %*% Hinv_e
    sigma_sq <- R / n
    return (as.numeric(sigma_sq))
}
```

```{r}
X <- as.matrix(covar_pheno[2:13])
sigmas.score <- rep(0, nCol)
deltas.score <- rep(0, nCol)

system.time({
    for (i in 1:nCol) {
        Y <- eval(parse(text=paste0("covar_pheno$V", i+1)))
        if (score_vce(0, Y) * score_vce(100, Y) > 0) {
            va <- 0
            # What if uniroot is unapplicable?
            formula <- as.formula(paste(paste0("V", i+1), "~ Sex + Age + PC1 + PC2 + PC3 + PC4 + PC5 + PC6 + PC7 + PC8 + PC9 + PC10"))
            resid1 <- resid(lm(formula, data=covar_pheno))
            ve <- sum(resid1 * resid1) / n
        } else {
            opt <- uniroot(score_vce, interval=c(0, 100), Y=Y)        
            opt_delta <- opt$root
            va <- sigma_sq(opt_delta, Y)
            ve <- opt_delta * va
        }
        sigmas.score[i] <- ve
        deltas.score[i] <- va/ve
    }
})
# 10~11 min for 1485 phenotypes
```

# Compare results

```{r}
sigmas.mom[1:50]
sigmas.score[1:50]
```


```{r}
length(which(deltas.mom > 0))
length(which(deltas.score > 0))
```

```{r}
deltas.mom[1:10]
deltas.score[1:10]
```

```{r}
plot(sigmas.mom, sigmas.score)
```

```{r}
plot(deltas.mom, deltas.score, xlim=c(-0.5, 5), ylim=c(-0.5, 5))
herit.mom <- deltas.mom / (deltas.mom + 1)
herit.score <- deltas.score / (deltas.score + 1)
herit.mom[herit.mom > 1] <- 1
plot(herit.mom, herit.score)
```

# Herit.mom vs herit.score
```{r}
model1 <- lm(herit.score ~ herit.mom - 1)
summary(model1)
```

## e_i e_j vs K_ij

```{r}
eiej <- rep(0, nrow(kinship))
i <- 66
formula <- as.formula(paste(paste0("V", i+1), "~ Sex + Age + PC1 + PC2 + PC3 + PC4 + PC5 + PC6 + PC7 + PC8 + PC9 + PC10"))
resid1 <- resid(lm(formula, data=covar_pheno))
for (i in 1:nrow(kinship)) {
    eiej[i] <- resid1[kinship[i,4]] * resid1[kinship[i,5]]
}
moment_reg <- lm(eiej ~ kinship$value - 1)
coeff_mom <- moment_reg$coefficients
coeff_mom
plot(kinship$value, eiej)
```
